#!/usr/bin/env bash
#
#The MIT License (MIT)
#
#Copyright (c) 2014 Research Compendia
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


# This script calls the author's R script with no ability to change parameters at this time.

set -e

mkdir -p compendiaoutput

# This behaves like "Knit HTML" in RStudio
Rscript knit_html.R  &> output.txt

# it rebuilds
#  figure/unnamed-chunk-3.png
#  reproducing-bicycle-helmet-research.html
#  reproducing-bicycle-helmet-research.md

for filename in output.txt reproducing-bicycle-helmet-research.html reproducing-bicycle-helmet-research.md figure/unnamed-chunk-3.png; do
    if [ -f $filename ]; then
        cp $filename compendiaoutput/
    fi
done
